package controllers

import (
	"go-api/gin-api/entities"
	"net/http"

	"github.com/gin-gonic/gin"
)

type tweetController struct {
	tweets []entities.Tweet
}

func NewTweetController() *tweetController {
	tc := tweetController{}
	return &tc
}

func (tc *tweetController) FindAll(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, tc.tweets)
}

func (tc *tweetController) Create(ctx *gin.Context) {
	tweet := entities.NewTweet()

	// BindJSON merges info from tweet (id autogenerated) with incoming data
	if err := ctx.BindJSON(&tweet); err != nil {
		return
	}

	tc.tweets = append(tc.tweets, *tweet)

	ctx.JSON(http.StatusOK, tc.tweets)
}

func (tc *tweetController) Delete(ctx *gin.Context) {
	id := ctx.Param("id")

	for idx, tweet := range tc.tweets {
		if tweet.ID == id {
			tc.tweets = append(tc.tweets[0:idx], tc.tweets[idx+1:]...)
			return
		}
	}

	ctx.JSON(http.StatusNotFound, gin.H{
		"error": "Tweet not found",
	})
}
